-- AlterTable
ALTER TABLE `RequestLog`
  MODIFY `status` ENUM('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'REJECTED_RATE_LIMIT', 'REJECTED_AUDIT', 'QUEUE_TIMEOUT') NOT NULL,
  MODIFY `latencyMs` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3);
